# Fly.io deployment configuration for Sango Text Sim
app = "sango-text-sim"
primary_region = "lax"  # Los Angeles - change as needed

[build]
  [build.args]
    PYTHON_VERSION = "3.11"

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.concurrency]]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
