# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information

app = "sango-text-sim-web"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "8080"
