name: Run Tests

on:
  push:
    branches: [ main, feature/web-interface-and-deployment ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with pytest
      run: |
        python -m pytest --cov=src --cov=app --cov-report=term-missing --cov-report=xml
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v5
      if: always()
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
